### ISSUE TITLE
Upgrade to Null Safety package

### ISSUE THREAD

**Issue by iqfareez** [medyas/flutter_qiblah#12]
Issue with **`Geolocator`**

```
So, because <myapp> depends on both geolocator ^7.0.1 and flutter_qiblah ^1.0.3+2, version solving failed.
pub get failed 
exit code 1
```

**Comment by medyas** [comment]
Currently there is a problem when migrating to Null safety:
```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:flutter_compass
```

so the flutter_compass packages needs to be migrated first.
will try to find a solution in the next couple of days, in the meantime you can get the migrated version of the master branch

**Comment by iqfareez** [comment]
Looks like [`flutter_compass`](https://pub.dev/packages/flutter_compass) has been migrated to null safety. :eyes:

**Comment by medyas** [comment]
@iqfareez thnx, just published V2 of the plugin.
