### ISSUE TITLE
Manual Location Support

### ISSUE THREAD

**Issue by hamadkhan0099** [medyas/flutter_qiblah#15]
@medyas  bro how can we modify it for manual latitude and longitude? Can you provide some urgent support, it will be appreciated.

**Comment by medyas** [comment]
you will need the heading to find Qibla direction

**Comment by medyas** [comment]
if you want to input the lat/lng then you can use the flutter_compass  directly and calculate the angle

**Comment by hamadkhan0099** [comment]
@medyas bro i am very new to flutter can you help me for manual location of qiblah with coding example because i am stuck with location stream which you have used. If you provide code of it, it will be appreciated  😊

**Comment by medyas** [comment]
unfortunately, i don't have time.
but you can check the source of the plugin and use flutter_compass directly.
