### ISSUE TITLE
Drain issue, please fix the following

### ISSUE THREAD

**Issue by S1nPur1ty** [medyas/flutter_qiblah#2]
First of all, thank you so much for the help dear brother! I noticed that in the dispose method, you forgot the use .drain() functionality before disposing it, so here is the fix.

Please update your dispose method:
```
 /// Close compass stream, and set Qiblah stream to null
  dispose() async {
    await _qiblahStream.drain();
    _qiblahStream = null;
    FlutterCompass().dispose();
  }
```

**Comment by medyas** [comment]
I did not forgot, calling `drain `is not a common things, as it will probably cause this error : [Calling Drain on a Stream](https://stackoverflow.com/a/57512815/8738574) . Both of compass and location stream will never stop emitting, and so if we call `drain `it will never complete.

**Comment by S1nPur1ty** [comment]
> I did not forgot, calling `drain `is not a common things, as it will probably cause this error : [Calling Drain on a Stream](https://stackoverflow.com/a/57512815/8738574) . Both of compass and location stream will never stop emitting, and so if we call `drain `it will never complete.
> Your welcome to make a fork and test it.

Thanks for providing this source. I will let you know when changes take place.
