### ISSUE TITLE
Upgrade flutter_compass to 0.7.0

### ISSUE THREAD

**Issue by mahmoud-haj-ali** [medyas/flutter_qiblah#20]

**Comment by boymustafa** [comment]
Is there any update on this issue? Apparently, I also have the same issue, I can t update flutter_compass to 0.7.0 because flutter qiblah depends on the flutter compass 0.6.1.

**Comment by medyas** [comment]
will try to do this later today

**Comment by medyas** [comment]
updated in the latest release: `flutter_qiblah: ^2.0.2`
