### ISSUE TITLE
Add the project to Awesome Muslim List 

### ISSUE THREAD

**Issue by choubari** [medyas/flutter_qiblah#22]
In [this repository](https://github.com/choubari/awesome-Muslims), I've collected open source projects, free tools and resiurces that could help developers and encourage them produce more islamic apps. 

It would be great to add this project under the [Libraries & Plugins > Dart & Flutter](https://github.com/choubari/Awesome-Muslims#dart--flutter) Section.

Thank you !

**Comment by medyas** [comment]
@choubari I prefer keeping the project under my account so i could continue maintaining it. Your welcome to copy the repo there or provide a link to this one.
