### ISSUE TITLE
it is lagging its not smoothly animating 

### ISSUE THREAD

**Issue by mohmmad47** [medyas/flutter_qiblah#23]
hello i am new to flutter and i found this package and it is use full but there is one problem its not animating guys if you have any suggestions please let me know

**Comment by medyas** [comment]
@mohmmad47 have you run the example app ?

**Comment by mohmmad47** [comment]
yes and its lagging too example not rendering at 60 fps its rendering at 10 fps max

**Comment by medyas** [comment]
are you testing the release build ? or debug

**Comment by mohmmad47** [comment]
release build and debug both

**Comment by medyas** [comment]
okay, will try to check this in the weekend

**Comment by mohmmad47** [comment]
may be i know the reason its because flutter compass has given the update and there was lag in the version so will you please downgrade the version it will be best or as you wish
