### ISSUE TITLE
It's lagging, not working smoothly

### ISSUE THREAD

**Issue by AliPunjabi** [medyas/flutter_qiblah#24]
direction is correct but needle moves slowly

**Comment by medyas** [comment]
@AliPunjabi well this depends on the device emitted data & not related to the plugin

**Comment by AliPunjabi** [comment]
@medyas On what basis are you saying this? I have checked it on various devices

**Comment by medyas** [comment]
@AliPunjabi tested on emulator or an iphone device

**Comment by AliPunjabi** [comment]
@medyas tested on simulator and on android device, but don't close it now, wait, I'm going to test on iphone.

**Comment by AliPunjabi** [comment]
@medyas If there will be no problem, I will close it myself

**Comment by AliPunjabi** [comment]
@medyas yes you were right, its depend on device, working well on Iphone. Thanks a lot.
