### ISSUE TITLE
geolocator

### ISSUE THREAD

**Issue by shereefhamed** [medyas/flutter_qiblah#25]
Because flutter_qiblah >=2.0.2 depends on geolocator ^7.6.0 and depends on geolocator ^8.0.0, flutter_qiblah >=2.0.2 is forbidden.
So, because uber depends on flutter_qiblah ^2.0.2, version solving failed.
pub get failed (1; So, because uber depends on flutter_qiblah ^2.0.2, version solving failed.)

**Comment by medyas** [comment]
@shereefhamed noting to do with this package.
You have version conflicts between the used packages. you can either override or downgrade the package version
