### ISSUE TITLE
desnt work with geolocator latest version

### ISSUE THREAD

**Issue by SpicierEwe** [medyas/flutter_qiblah#26]

**Comment by medyas** [comment]
Could you provide more details !

**Comment by SpicierEwe** [comment]
> Could you provide more details !

Because flutter_qiblah 2.0.2 depends on geolocator ^7.6.0 and no versions of flutter_qiblah match >2.0.2 <3.0.0, flutter_qiblah ^2.0.2 requires geolocator ^7.6.0.
So, because as_salah depends on both geolocator ^8.2.0 and flutter_qiblah ^2.0.2, version solving failed.
pub get failed (1; So, because as_salah depends on both geolocator ^8.2.0 and flutter_qiblah ^2.0.2, version solving failed.)

**Comment by medyas** [comment]
this is a version conflicts, adnd can be fixed by overriding the dependencies.
```Dart
dependency_overrides:
  geolocator : ^8.2.0
```

**Comment by SpicierEwe** [comment]
> 
thank you

**Comment by SpicierEwe** [comment]
do u know here can i get authentic ramadan calendar api?

**Comment by medyas** [comment]
@SpicierEwe sorry did not see you comment. Unfortunately i don't.

**Comment by SpicierEwe** [comment]
> @SpicierEwe sorry did not see you comment. Unfortunately i don't.

No problem 
Assalamualaikum warahmatullahi wabarakatuhu
