### ISSUE TITLE
Compass UI customization possible??

### ISSUE THREAD

**Issue by wackyapps** [medyas/flutter_qiblah#27]
Is this compass plugin allow customization of UI
See the below image. Does, this plugin allow to make changes to bring it closer to the image attached.

![image](https://user-images.githubusercontent.com/1482426/158359330-9033aeeb-c4f7-400a-82d8-ec6c2ac90406.png)

**Comment by medyas** [comment]
@wackyapps the plugin it self does not provide any UI by default, its the logic about the direction and you can customize your UI to what ever suits you

**Comment by wackyapps** [comment]
> @wackyapps the plugin it self does not provide any UI by default, its the logic about the direction and you can customize your UI to what ever suits you

Do you recommend any way you know to implement Qibla Compas using your plugin with any UI?
