### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by wackyapps** [medyas/flutter_qiblah#28]
E/flutter ( 1808): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
E/flutter ( 1808): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:175
E/flutter ( 1808): <asynchronous suspension>
E/flutter ( 1808): #1      MethodChannelPermissionHandler.checkPermissionStatus
package:permission_handler_platform_interface/…/method_channel/method_channel_permission_handler.dart:16
E/flutter ( 1808): <asynchronous suspension>
E/flutter ( 1808):

![image](https://user-images.githubusercontent.com/1482426/159086376-8bb853e1-ca83-47d0-bf45-1a81b197b544.png)

![image](https://user-images.githubusercontent.com/1482426/159086406-60a13bf8-df83-48f9-aaf9-400de0129374.png)

My Pubspec.yaml

![image](https://user-images.githubusercontent.com/1482426/159086498-3e79da0e-d13a-4369-aca6-bc440987c014.png)

**Comment by wackyapps** [comment]
@medyas would you help me on this?

**Comment by medyas** [comment]
@wackyapps the issue is happening because the `dependency_override`. If you remove it, you won't have this crash.
will try to update the package dependencies on i have time

**Comment by AhmedElhenidy** [comment]
just make flutter clean
uninstall the app
then run

**Comment by maah75** [comment]
Greeting I have the same issue 

`Because flutter_qiblah >=2.0.2 depends on geolocator ^7.6.0 and ... depends on geolocator ^8.2.0, flutter_qiblah >=2.0.2 is forbidden.`

Please if you can help us with update

**Comment by AhmedElhenidy** [comment]
change geolocator from 8.2.0 to 7.6.0
