### ISSUE TITLE
 No podspec found for `flutter_qiblah_update` in `.symlinks/plugins/flutter_qiblah_update/iOS` 

### ISSUE THREAD

**Issue by ArslanKhan99** [medyas/flutter_qiblah#33]
No podspec found for `flutter_qiblah_update` in `.symlinks/plugins/flutter_qiblah_update/ios`

**Comment by medyas** [comment]
@ArslanKhan99 i don't have a Mac, if you could test and provide more details about the issue

**Comment by ArslanKhan99** [comment]
This is actually the reason I think you can build Mac pod spec only from Mac

**Comment by medyas** [comment]
@ArslanKhan99 is this fixed for you ?
