### ISSUE TITLE
Compass not working on iOS

### ISSUE THREAD

**Issue by Hesham-Dev-LY** [medyas/flutter_qiblah#39]
I am experiencing an issue with the compass functionality on iOS. Specifically, the compass does not display and remains stuck on a loading indicator on `AsyncSnapshot<LocationStatus>`. There are no error messages printed to the console.

Here are some additional details about the issue:

- Location services are enabled and permission has been granted.
- The issue is specific to iOS; the compass works as expected on other platforms.
- The device is running the latest version of iOS.
- The issue occurs consistently and cannot be resolved by restarting the app or the device.
- I have attempted to troubleshoot the issue by checking the relevant permissions and reviewing the code that relates to the compass functionality, but so far I have not been able to identify the root cause of the issue.

I would greatly appreciate any assistance in resolving this issue, as the compass functionality is a critical feature of our app. Thank you in advance for your help.

**Comment by medyas** [comment]
@Hesham-Dev-LY are you testing this on a real device ? or Simulator ?

**Comment by Hesham-Dev-LY** [comment]
I apologize for any confusion caused. After testing the app on a real iPhone, I found that it works fine. It seems that the issue I was experiencing was specific to the iOS simulator.

Please go ahead and close this issue. However, I wanted to suggest adding a note to the README file indicating that the app may not work properly in the iOS simulator.

Thanks for your help!

Best regards,
Hesham
