### ISSUE TITLE
flutter_qiblah not compatible with newer Android gradle versions

### ISSUE THREAD

**Issue by diegobarle-dev** [medyas/flutter_qiblah#40]
> The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
> The following dependencies do not satisfy the required version:
> project ':flutter_qiblah' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61

Starting from version `'com.android.tools.build:gradle:7.3.0'`

Meaning that projects have to fix their gradle versions and not being able to update it just to support this library.

**Comment by medyas** [comment]
fix in latest version
