### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by ruhul080** [medyas/flutter_qiblah#50]
Execution failed for task ':flutter_qiblah:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (1.8) and 'compileDebugKotlin' (17).

Probably you need to support kotlin >= 1.8

Newer version does not support.

**Comment by medyas** [comment]
@ruhul080 The package supports Java 17. So you need to update your project to support it.
```dart
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
```
