### ISSUE TITLE
How can I know if its facing the qibla.

### ISSUE THREAD

**Issue by heymars** [medyas/flutter_qiblah#52]
Hi ,

I want to understand how I can accomplish this — I aim to turn the screen background green if it's facing the qibla direction.

**Comment by medyas** [comment]
you can do this by checking if `qiblahDirection.qiblah == qiblahDirection.offset`

**Comment by heymars** [comment]
Hi @medyas Thanks for the reply but this is not working while` qiblahDirection.qiblah` giving value `719.68` and `qiblahDirection.offset` giving  value `-79.002` , ` qiblahDirection.qiblah` never gives the values same as `qiblahDirection.offset`
