### ISSUE TITLE
Loading indicator in iOS

### ISSUE THREAD

**Issue by Nanank-kho** [medyas/flutter_qiblah#6]
in iOS maps and qiblah not show, only loading indicator,.
![Simulator Screen Shot - iPhone 11 - 2020-09-06 at 13 26 57](https://user-images.githubusercontent.com/12078569/92319686-36bd3280-f045-11ea-939f-90bb4c45aed9.png)

**Comment by medyas** [comment]
Are you testing the example app ?

**Comment by Nanank-kho** [comment]
Yes, I testing Example app

**Comment by medyas** [comment]
okay, Will try to test it in the next couple of days

**Comment by Fireballion** [comment]
Any luck on this? I am looking into Qiblah for a project and am wondering if this is a reproducing error?

**Comment by medyas** [comment]
@Fireballion have not been able to test this yet

**Comment by medyas** [comment]
@Nanank-kho  @Fireballion have test the plug in in iOS and it turned out that the example app does not contain location permission in the infoP.list . I have added the permissions to the file and pushed to the master branch, you can now pull from master and test again and it should work.

**Comment by Nanank-kho** [comment]
Yeah many Thanks, it's Work fine..
And how to show Maps directions below the Compass ?
In Example Will check device support, if support sensor show Compass, and if not support show Maps,.

**Comment by medyas** [comment]
@Nanank-kho well the example app is set to show compass if the device has the needed hardware, else it will show the map direction. You edit the implementation in your app and show them both.
