### ISSUE TITLE
Wrong direction

### ISSUE THREAD

**Issue by uni-united** [medyas/flutter_qiblah#7]
The qiblah direction its showing is not correct. Please update Am from India, Its showing wrong direction

**Comment by medyas** [comment]
Hi @uni-united 
This plugin is using the flutter_compass plugin to get the North direction, which uses the phone hardware to determine this. In Android devices the hardware is not very good and keeps giving wrong direction but if you test it in iOS, you will find that its working properly. 
This is not a problem with the Qiblah direction but with the North direction, and is related to flutter_compass plugin.
