### ISSUE TITLE
Qibla map real time location movement 

### ISSUE THREAD

**Issue by moosalim** [medyas/flutter_qiblah#8]
Hello and thanks for this plugin, very helpful

I am new to flutter, and I wanted to use this plugin, but I just noticed one issue with the qibla maps related to the realtime location adjustment.

When the qibla map page opened, the line to Mecca will show along the location appearing at that time, but location is getting automatically adjusted to be more accurate and therefore it moves, where as the line to Mecca remain where it was without moving along the location. 

I believe and as I have seen in other apps, the line should move with the location as it get adjusted.

can you please fix this.

**Comment by medyas** [comment]
@moosalim this is not related to the plug in, as the map part is an extra added to the example app. You should be able to develop this in your own app, you can use the geolocator plug in to get user current location and update the marker and path based on it.
will close this as it not related to the plugin it self.

**Comment by moosalim** [comment]
I am very new to coding and I could not do it by myself. Can please help to update example code to achieve this feature.

**Comment by medyas** [comment]
i will see it i can manage to do it in the weekend

**Comment by moosalim** [comment]
Hello brother

Can you please spare sometime to do this. I kindly appreciate this from you.

**Comment by medyas** [comment]
will try to do it ASAP.

**Comment by moosalim** [comment]
Gentle reminder please about this

**Comment by medyas** [comment]
sorry, really forgot about this, will try to remember it this weekend and do it

**Comment by moosalim** [comment]
Thank you very much, your support on this is highly appreciated .
