### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by arayhann** [medyas/flutter_qiblah#9]
Because no versions of camerawesome match >0.2.1+2 <0.3.0 and camerawesome 0.2.1+2 depends on rxdart ^0.25.0, camerawesome ^0.2.1+2 requires rxdart ^0.25.0.
And because flutter_qiblah >=1.0.3+2 depends on flutter_compass ^0.5.0 which depends on rxdart ^0.24.1, camerawesome ^0.2.1+2 is incompatible with flutter_qiblah >=1.0.3+2.
So, because hijrah_merchants depends on both flutter_qiblah ^1.0.3+2 and camerawesome ^0.2.1+2, version solving failed.
pub get failed (1; So, because hijrah_merchants depends on both flutter_qiblah ^1.0.3+2 and camerawesome ^0.2.1+2, version solving failed.)

I need both dependencies for my app, any way to fix this?

**Comment by medyas** [comment]
try : 

```
dependency_overrides:
  rxdart: ^0.25.0
```
